### PR TITLE
190-added-in-link-to-index

### PR DESCRIPTION
**Pull request by darrylpargeter**
Adds in feature requested in #190 

I have added a button that takes the user from the first-run.html page to index.html
# Starting State:
lightbeam_button_no_hover

# Hovering State:
lightbeam_button_with_hover

### CODE REVIEW

**Comment by jonathanKingston** [comment]
Hey this looks great!

Can you change the "clicking the link below" to "using the 'Get Started' below".
Then change "Click Here To Get Started" to "Get Started"

Rationale is, we should allow keyboard navigation. I'm less worried about the browser action as the primary action is clicking but if you can think of better wording to that would be great.

**Comment by darrylpargeter** [comment]
Hey @jonathanKingston I have update the PR with though changes.

**Comment by jonathanKingston** [comment]
LGTM thanks @darrylpargeter, currently we don't display this page as we didn't have the code in place to run on install vs update. So I disabled it, will raise a follow up bug.

**Comment by darrylpargeter** [comment]
Hey @jonathanKingston  when you have created that ticket would it be possible to tackle it?

**Pull request merged**
